"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var User_1 = require("./src/Model/User");
var laptop_1 = require("./src/Model/Products/laptop");
var TV_1 = require("./src/Model/Products/TV");
var Phone_1 = require("./src/Model/Products/Phone");
var main_1 = require("./src/main");
var main = new main_1.Main();
var laptop1 = new laptop_1.Laptop("HP G850", 2000, "HP", 32, "Core i9 13 Gen", "RTX4090", 512);
var phone1 = new Phone_1.Phone("S20", 400, "Sumsung", 5000, 108);
var tv1 = new TV_1.TV("Sumsung 2", 500, "Sumsung", 32, false, "Amoled");
var tv2 = new TV_1.TV("Sumsung 2", 500, "Sumsung", 32, false, "Amoled");
main.addProducts(laptop1, phone1, tv1, tv2);
console.log(main.getProductsList());
// console.log(main.showProducts("Tv"));
main.signUp("Nurullo", "karimov_nurulloh", "root123");
main.signUp("Nurullo", "karimov_nurullo", "root123");
var user1 = new User_1.User("Nurullo", "nurullo", "root123", 11222);
var user2 = new User_1.User("Ronaldo", "cristiano", "cr7", 11222999999);
var user3 = new User_1.User("Amirxon", "abralov", "amirxon_2008", 19999);
main.addUsers(user1, user2, user3);
console.log("Users list: ", main.getUsersList());
// console.log("Admin :", main.checkAdmin(user3));
